config/routes.rb
Web::Application.routes.draw do

#    resources :sessions, :constraints => { :protocol => "https" }
#  end
#  Or if you need to force SSL for multiple routes:
#
#  MyApplication::Application.routes.draw do
  get "content_flags/new"
#    scope :constraints => { :protocol => "https" } do
#      # All your SSL routes.
#    end
#  end

#  scope :constraints => { :protocol => "https" } do
    devise_for :users, controllers: { sessions: "users/sessions",
                                      passwords: "users/passwords",
                                      confirmations: "users/confirmations",
                                      registrations: "users/registrations"
                                    }

    devise_scope :user do
      get 'users/suggestuniqueuname', :to => "users/registrations#suggestuniqueuname"
      get 'users/passwordchanged', :to => "users/passwords#changed"
      get 'users/emailconfirmed', :to=> "users/confirmations#emailconfirmed"
    end

#  resources :users, only: [ :show, :update, :profile, :edit, :index ] do
    resources :users do
      collection do
        get 'lookupname'
  #      get 'friends',       :to => "connections#friends"
        get 'following',     :to => "connections#following"
        get 'followers',     :to => "connections#followers"
        get 'followerrequests', :to => "connections#followerrequests"
        put 'updateapnstoken'
        put 'invitetoflux', :to =>"users#invitetoflux"
        get 'invitetoflux', :to =>"users#invitetoflux"
      end
      member do
        get 'profile'
        get 'user'
        get 'avatar', :protocol => "http"
#        get 'validateemail'
      end
    end

    resources :images do
      collection do
        get 'filtered'  # more comprehensive filtering of queries
        get 'filteredcontent' # filtered but returning only lat, lon, alt, imageid, type
        get 'filteredimgcounts'      # returns total image count, count of my images, count of friends images and count of following images
        get 'getimagelistforuser'    # returns list of [id, description] pairs, ordered by time_stamp [DESC] with the given userid
        get 'nuke'
        put 'setprivacy'
        patch 'setprivacy'
      end
      member do
        get 'image', :protocol => "http"
        get 'renderimage', :protocol => "http"
        get 'historical', :protocol => "http"
        get 'features', :protocol => "http"
        get 'matches',  :to => "image_matches#getmatches"   # return set of image match records for the specified image
        post 'flag', :to => "content_flags#flag"
        put 'setdescription'
        patch 'setdescription'
      end
    end

    resources :cameras do
      collection do
        get 'lookupbydevid'  # camera that matches specified deviceid
      end
      member do
        get 'camera'
      end
    end

    resources :tags do
      collection do
        get 'localbycountfiltered'
        get 'localbycount'
        get 'bycount'
      end
      member do
        get 'tag'
      end
    end

    resources :aliases do
      collection do
        get 'importcontacts'
        get 'foruser'
      end
      member do
        get 'alias'
      end
    end

    resources :connections do
      collection do
        post 'follow'
        put  'disconnect'
        put  'respondtofollowrequest'
      end
      member do
      end
    end
#  end

#  resources :image_matches do
#    collection do
#    end
#    member do
#      get 'matches'
#    end
#  end

end

app/models/camera.rb
class Camera < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection

  belongs_to :user
  has_many :images, dependent: :destroy

  validates_presence_of :user, :deviceid

  def to_s; nickname; end
end

app/controllers/cameras_controller.rb
class CamerasController < ApplicationController

  before_filter :authenticate_user_from_token!
  before_filter :authenticate_user!
  authorize_resource

  # GET /cameras
  # GET /cameras.json
  def index
    @cameras = Camera.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cameras }
    end
  end

  # GET /cameras/1
  # GET /cameras/1.json
  def show
    @camera = Camera.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @camera }
    end
  end

  # GET /cameras/lookupbydevid?deviceid=xxx
  # GET /cameras/lookupbydevid.json?deviceid=xxx
  def lookupbydevid
    @camera = Camera.where(deviceid: params[:deviceid])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @camera }
    end
  end

  
  # GET /cameras/new
  # GET /cameras/new.json
  def new
    @camera = Camera.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @camera }
    end
  end

  # GET /cameras/1/edit
  def edit
    @camera = Camera.find(params[:id])
  end

  # POST /cameras
  # POST /cameras.json
  def create
#    @camera = Camera.new(camera_params)
    @camera = Camera.where(deviceid: camera_params[:deviceid]).first_or_create(camera_params)
    if (!camera_params[:app_version].nil?)
      if (@camera[:app_version] != camera_params[:app_version])
        # update the version...
        if (@camera[:app_version].nil?)
          logger.debug "old app version: nil, new version: " + camera_params[:app_version]
        else
          logger.debug "old app version: " + @camera[:app_version] + ", new version: " + camera_params[:app_version]
        end
        @camera.update_attributes(camera_params)
      end
    end

    respond_to do |format|
      if @camera.save
        format.html { redirect_to @camera, notice: 'Camera was successfully created/updated.' }
        format.json { render json: @camera, status: :created, location: @camera }
      else
        format.html { render action: "new" }
        format.json { render json: @camera.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cameras/1
  # PATCH/PUT /cameras/1.json
  def update
    @camera = Camera.find(params[:id])

    respond_to do |format|
      if @camera.update_attributes(camera_params)
        format.html { redirect_to @camera, notice: 'Camera was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @camera.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cameras/1
  # DELETE /cameras/1.json
  def destroy
    @camera = Camera.find(params[:id])
    @camera.destroy

    respond_to do |format|
      format.html { redirect_to cameras_url }
      format.json { head :no_content }
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def camera_params
      params.require(:camera).permit(:description, :deviceid, :model, :nickname, :user_id, :app_version)
    end
end

app/helpers/cameras_helper.rb
module CamerasHelper
end

app/views/cameras/_form.html.erb
<%= form_for(@camera) do |f| %>
  <% if @camera.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@camera.errors.count, "error") %> prohibited this camera from being saved:</h2>

      <ul>
      <% @camera.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :deviceid %><br />
    <%= f.text_field :deviceid %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cameras/edit.html.erb
<h1>Editing camera</h1>

<%= render 'form' %>

<%= link_to 'Show', @camera %> |
<%= link_to 'Back', cameras_path %>

app/views/cameras/index.html.erb
<h1>Listing cameras</h1>

<table>
  <tr>
    <th>User</th>
    <th>Model</th>
    <th>Deviceid</th>
    <th>Description</th>
    <th>Nickname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cameras.each do |camera| %>
  <tr>
    <td><%= camera.user %></td>
    <td><%= camera.model %></td>
    <td><%= camera.deviceid %></td>
    <td><%= camera.description %></td>
    <td><%= camera.nickname %></td>
    <td><%= link_to 'Show', camera %></td>
    <td><%= link_to 'Edit', edit_camera_path(camera) %></td>
    <td><%= link_to 'Destroy', camera, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Camera', new_camera_path %>

app/views/cameras/new.html.erb
<h1>New camera</h1>

<%= render 'form' %>

<%= link_to 'Back', cameras_path %>

app/views/cameras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @camera.user %>
</p>

<p>
  <b>Model:</b>
  <%= @camera.model %>
</p>

<p>
  <b>Deviceid:</b>
  <%= @camera.deviceid %>
</p>

<p>
  <b>Description:</b>
  <%= @camera.description %>
</p>

<p>
  <b>Nickname:</b>
  <%= @camera.nickname %>
</p>


<%= link_to 'Edit', edit_camera_path(@camera) %> |
<%= link_to 'Back', cameras_path %>