config/routes.rb
Web::Application.routes.draw do

#    resources :sessions, :constraints => { :protocol => "https" }
#  end
#  Or if you need to force SSL for multiple routes:
#
#  MyApplication::Application.routes.draw do
  get "content_flags/new"
#    scope :constraints => { :protocol => "https" } do
#      # All your SSL routes.
#    end
#  end

#  scope :constraints => { :protocol => "https" } do
    devise_for :users, controllers: { sessions: "users/sessions",
                                      passwords: "users/passwords",
                                      confirmations: "users/confirmations",
                                      registrations: "users/registrations"
                                    }

    devise_scope :user do
      get 'users/suggestuniqueuname', :to => "users/registrations#suggestuniqueuname"
      get 'users/passwordchanged', :to => "users/passwords#changed"
      get 'users/emailconfirmed', :to=> "users/confirmations#emailconfirmed"
    end

#  resources :users, only: [ :show, :update, :profile, :edit, :index ] do
    resources :users do
      collection do
        get 'lookupname'
  #      get 'friends',       :to => "connections#friends"
        get 'following',     :to => "connections#following"
        get 'followers',     :to => "connections#followers"
        get 'followerrequests', :to => "connections#followerrequests"
        put 'updateapnstoken'
        put 'invitetoflux', :to =>"users#invitetoflux"
        get 'invitetoflux', :to =>"users#invitetoflux"
      end
      member do
        get 'profile'
        get 'user'
        get 'avatar', :protocol => "http"
#        get 'validateemail'
      end
    end

    resources :images do
      collection do
        get 'filtered'  # more comprehensive filtering of queries
        get 'filteredcontent' # filtered but returning only lat, lon, alt, imageid, type
        get 'filteredimgcounts'      # returns total image count, count of my images, count of friends images and count of following images
        get 'getimagelistforuser'    # returns list of [id, description] pairs, ordered by time_stamp [DESC] with the given userid
        get 'nuke'
        put 'setprivacy'
        patch 'setprivacy'
      end
      member do
        get 'image', :protocol => "http"
        get 'renderimage', :protocol => "http"
        get 'historical', :protocol => "http"
        get 'features', :protocol => "http"
        get 'matches',  :to => "image_matches#getmatches"   # return set of image match records for the specified image
        post 'flag', :to => "content_flags#flag"
        put 'setdescription'
        patch 'setdescription'
      end
    end

    resources :cameras do
      collection do
        get 'lookupbydevid'  # camera that matches specified deviceid
      end
      member do
        get 'camera'
      end
    end

    resources :tags do
      collection do
        get 'localbycountfiltered'
        get 'localbycount'
        get 'bycount'
      end
      member do
        get 'tag'
      end
    end

    resources :aliases do
      collection do
        get 'importcontacts'
        get 'foruser'
      end
      member do
        get 'alias'
      end
    end

    resources :connections do
      collection do
        post 'follow'
        put  'disconnect'
        put  'respondtofollowrequest'
      end
      member do
      end
    end
#  end

#  resources :image_matches do
#    collection do
#    end
#    member do
#      get 'matches'
#    end
#  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  before_filter :authenticate_user_from_token!
  before_filter :authenticate_user!, except: [ :renderimage ]

  # GET /images
  # GET /images.json
  def index
    @images = params[:ids].present? ? Image.where(id: params[:ids].split(',')) : Image.order("time_stamp DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @images }
    end
  end

  # GET /images/filtered?lat=...&long=...&radius=...&minalt=...&maxalt=...
  #                     &mintime=...&maxtime=...
  #                     &taglist="tag1 tag2 tag3...tagN"
  #                     &userlist="user1 user2 user3...userN"
  #                     &catlist="cat1 cat2...catN"
  def filtered
    mypics = params[:mypics]
    if mypics.nil?
      mypics = 0;
    end

    followingpics = params[:followingpics]
    if followingpics.nil?
      followingpics = 0;
    end

    @images = Image.filteredmeta(params[:auth_token], params[:lat], params[:long], params[:radius],
                                params[:altmin], params[:altmax],
                                params[:timemin], params[:timemax],
                                params[:taglist], params[:userlist],
                                mypics, followingpics, params[:maxcount])

    respond_to do |format|
      format.html { render 'index' }
      format.json { render json: @images }
    end
  end

  # GET /images/filteredcontent?lat=...&long=...&radius=...&minalt=...&maxalt=...
  #                     &mintime=...&maxtime=...
  #                     &taglist="tag1 tag2 tag3...tagN"
  #                     &userlist="user1 user2 user3...userN"
  #                     &catlist="cat1 cat2...catN"
  #                     &maxcount=...
  def filteredcontent
    mypics = params[:mypics]
    if mypics.nil?
      mypics = 0
    end

    followingpics = params[:followingpics]
    if followingpics.nil?
      followingpics = 0
    end

    @images = Image.filteredcontent(params[:auth_token], params[:lat], params[:long], params[:radius],
                                params[:altmin], params[:altmax],
                                params[:timemin], params[:timemax],
                                params[:taglist], params[:userlist],
                                mypics, followingpics, params[:maxcount])

    respond_to do |format|
    #  format.html { render 'index' }
      format.json { render json: @images }
    end
  end

  # GET /images/getimagelistforuser?userid=...
  # GET /images/getimagelistforuser.json?userid=...
  def getimagelistforuser
    @images = Image.joins(:user).where(user_id: params[:userid]).select("images.id, users.username, description, privacy, time_stamp").order("time_stamp DESC")

    respond_to do |format|
      format.html { render 'index' }
      format.json { render json: @images }
    end
  end

  # GET /images/filteredimgcounts?lat=...&long=...&radius=...&minalt=...&maxalt=...
  #                     &mintime=...&maxtime=...
  #                     &taglist="tag1 tag2 tag3...tagN"
  #                     &userlist="user1 user2 user3...userN"
  #                     &auth_token=...
  def filteredimgcounts
    mypics = params[:mypics]
    if mypics.nil?
      mypics = 0
    end

    followingpics = params[:followingpics]
    if followingpics.nil?
      followingpics = 0
    end

    query = ::Image.filteredimgcounts(params[:auth_token], params[:lat], params[:long], params[:radius],
                                params[:altmin], params[:altmax],
                                params[:timemin], params[:timemax],
                                params[:taglist], params[:userlist],
                                mypics, followingpics)
    # This will issue a query, but only with the attributes we selected above.
    # It also returns a simple Hash, which is significantly more efficient than a
    # full blown ActiveRecord model.
    results = ActiveRecord::Base.connection.select_all(query)
    render json: results
  end


  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/1/image
  def image
    @image = Image.find(params[:id])
    if params[:size] == "binfeatures"
      params[:size] = "original"
      logger.debug 'jumping to features() with size ' + params[:size]
      self.features
    else
      path = @image.image.path(params[:size])

      if (!path.nil?)
        if (Rails.env == 'production') || (Rails.env == 'staging')
           url = @image.image.expiring_url(5, params[:size])
            fn = @image.image_file_name
            ct = @image.image_content_type
          data = open(url)
          send_data data.read, filename: fn, type: ct, disposition: :attachment
        else
          send_file path, disposition: :attachment
        end

  #      send_file @image.image.url(params[:size]), disposition: :attachment

      else
        respond_to do |format|
          format.json { head :no_content }
        end
      end
    end
  end

  # GET /images/1/historical
  def historical
    @image = Image.find(params[:id])
    path = @image.historical.path(params[:size])
    if (!path.nil?)
#      send_file @image.historical.url(params[:size]), disposition: :attachment
      if (Rails.env == 'production') || (Rails.env == 'staging')
         url = @image.historical.expiring_url(5, params[:size])
          fn = @image.historical_file_name
          ct = @image.historical_content_type
        data = open(url)
        send_data data.read, filename: fn, type: ct, disposition: :attachment
      else
        send_file path, disposition: :attachment
      end

    else
      respond_to do |format|
        format.json { head :no_content }
      end
    end
  end

  # GET /images/1/renderimage
  def renderimage
    @image = Image.find(params[:id])
    path = @image.historical.path(params[:size])

    if (path.nil?)
      url = @image.image.expiring_url(5, params[:size])
      fn = @image.image_file_name
      ct = @image.image_content_type
      path = @image.image.path(params[:size])
    else
      url = @image.historical.expiring_url(5, params[:size])
      fn = @image.historical_file_name
      ct = @image.historical_content_type
    end

    if (Rails.env == 'production') || (Rails.env == 'staging')
      #    send_file url, disposition: :attachment
      data = open(url)
      send_data data.read, filename: fn, type: ct, disposition: :attachment
    elsif (!path.nil?)
      send_file path, disposition: :attachment
    else
      respond_to do |format|
        format.json { head :no_content }
      end
    end

  end

  # GET /images/1/features
  def features
    @image = Image.find(params[:id])
    path = @image.features.path(params[:size])
    if (!path.nil?)
      url = @image.features.expiring_url(5, params[:size])
       fn = @image.features_file_name
       ct = @image.features_content_type
     data = open(url)
     send_data data.read, filename: fn, type: ct, disposition: :attachment

    else
      respond_to do |format|
        format.json { head :no_content }
      end
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    logger.debug "Into Images#create"
   @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render json: @image, status: :created, location: @image }
      else
        logger.debug "Image POST failure: " + @image.errors.to_hash(true).to_s
        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  #PATCH/PUT /images/setprivacy?privacy=<1|0>&imageids=<CSV list of image ids>&auth_token=...
  #PATCH/PUT /images/setprivacy.json?privacy=<1|0>&imageids=<CSV list of image ids>&auth_token=...
  def setprivacy
    @user = User.find_by_authentication_token(params[:auth_token])

    update_attrs = {privacy: params[:privacy]}
    update_ids = params[:image_ids].split(",").map(&:to_i)

    update_ids.each do |uid|
      @image = Image.where({user_id: @user.id, id: uid}).first
      if (!@image.nil?)
        @image.update_attributes(update_attrs)
      end
    end

    respond_to do |format|
      format.json { head :no_content }
    end
 end

#PATCH/PUT /images/setdescription?description=...&auth_token=...
#PATCH/PUT /images/setdescription.json?description=...&auth_token=...
def setdescription
  @user = User.find_by_authentication_token(params[:auth_token])

  update_attrs = {description: params[:description]}
  @image = Image.where({user_id: @user.id, id: params[:id]}).first
  if (!@image.nil?)
    @image.update_attributes(update_attrs)
  end

  respond_to do |format|
    format.json { head :no_content }
  end
end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end

  # DELETE /images/nuke.json?lat=...&long=...&radius=...
  def nuke

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :raw_latitude %><br />
    <%= f.text_field :raw_latitude %>
  </div>
  <div class="field">
    <%= f.label :raw_longitude %><br />
    <%= f.text_field :raw_longitude %>
  </div>
  <div class="field">
    <%= f.label :raw_altitude %><br />
    <%= f.text_field :raw_altitude %>
  </div>
  <div class="field">
    <%= f.label :horiz_accuracy %><br />
    <%= f.text_field :horiz_accuracy %>
  </div>
  <div class="field">
    <%= f.label :vert_accuracy %><br />
    <%= f.text_field :vert_accuracy %>
  </div>
  <div class="field">
    <%= f.label :best_latitude %><br />
    <%= f.text_field :best_latitude %>
  </div>
  <div class="field">
    <%= f.label :best_longitude %><br />
    <%= f.text_field :best_longitude %>
  </div>
  <div class="field">
    <%= f.label :best_altitude %><br />
    <%= f.text_field :best_altitude %>
  </div>
  <div class="field">
    <%= f.label :location_confidence %><br />
    <%= f.text_field :location_confidence %>
  </div>
  <div class="field">
    <%= f.label :raw_yaw %><br />
    <%= f.text_field :raw_yaw %>
  </div>
  <div class="field">
    <%= f.label :raw_pitch %><br />
    <%= f.text_field :raw_pitch %>
  </div>
  <div class="field">
    <%= f.label :raw_roll %><br />
    <%= f.text_field :raw_roll %>
  </div>
  <div class="field">
    <%= f.label :best_yaw %><br />
    <%= f.text_field :best_yaw %>
  </div>
  <div class="field">
    <%= f.label :best_pitch %><br />
    <%= f.text_field :best_pitch %>
  </div>
  <div class="field">
    <%= f.label :best_roll %><br />
    <%= f.text_field :best_roll %>
  </div>
  <div class="field">
    <%= f.label :raw_qw %><br />
    <%= f.text_field :raw_qw %>
  </div>
  <div class="field">
    <%= f.label :raw_qx %><br />
    <%= f.text_field :raw_qx %>
  </div>
  <div class="field">
    <%= f.label :raw_qy %><br />
    <%= f.text_field :raw_qy %>
  </div>
  <div class="field">
    <%= f.label :raw_qz %><br />
    <%= f.text_field :raw_qz %>
  </div>
  <div class="field">
    <%= f.label :best_qw %><br />
    <%= f.text_field :best_qw %>
  </div>
  <div class="field">
    <%= f.label :best_qx %><br />
    <%= f.text_field :best_qx %>
  </div>
  <div class="field">
    <%= f.label :best_qy %><br />
    <%= f.text_field :best_qy %>
  </div>
  <div class="field">
    <%= f.label :best_qz %><br />
    <%= f.text_field :best_qz %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :time_stamp %><br />
    <%= f.text_field :time_stamp %>
  </div>
  <div class="field">
    <%= f.label :camera_id %><br />
    <%= f.text_field :camera_id %>
  </div>
  <div class="field">
    <%= f.label :heading %><br />
    <%= f.text_field :heading %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<h1>Listing images</h1>

<table>
  <tr>
    <th>Raw latitude</th>
    <th>Raw longitude</th>
    <th>Raw altitude</th>
    <th>Best latitude</th>
    <th>Best longitude</th>
    <th>Best altitude</th>
    <th>Raw yaw</th>
    <th>Raw pitch</th>
    <th>Raw roll</th>
    <th>Best yaw</th>
    <th>Best pitch</th>
    <th>Best roll</th>
    <th>Raw qw</th>    
    <th>Raw qx</th>    
    <th>Raw qy</th>    
    <th>Raw qz</th>    
    <th>Best qw</th>    
    <th>Best qx</th>    
    <th>Best qy</th>    
    <th>Best qz</th>    
    <th>Description</th>
    <th>Category</th>
    <th>User</th>
    <th>Time Stamp</th>
    <th>Camera</th>
    <th>Heading</th>
    <th>Image</th>
    <th>Horiz Acc</th>
    <th>Vert Acc</th>
    <th>Location Conf</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @images.each do |image| %>
  <tr>
    <td><%= image.raw_latitude %></td>
    <td><%= image.raw_longitude %></td>
    <td><%= image.raw_altitude %></td>
    <td><%= image.best_latitude %></td>
    <td><%= image.best_longitude %></td>
    <td><%= image.best_altitude %></td>
    <td><%= image.raw_yaw %></td>
    <td><%= image.raw_pitch %></td>
    <td><%= image.raw_roll %></td>
    <td><%= image.best_yaw %></td>
    <td><%= image.best_pitch %></td>
    <td><%= image.best_roll %></td>
    <td><%= image.raw_qw %></td>
    <td><%= image.raw_qx %></td>
    <td><%= image.raw_qy %></td>
    <td><%= image.raw_qz %></td>
    <td><%= image.best_qw %></td>
    <td><%= image.best_qx %></td>
    <td><%= image.best_qy %></td>
    <td><%= image.best_qz %></td>
    <td><%= image.description %></td>
    <td><%= image.category %></td>
    <td><%= image.user %></td>
    <td><%= image.time_stamp %></td>
    <td><%= image.camera %></td>
    <td><%= image.heading %></td>
    <td><%= image_tag image.image.url :thumb %></td>
    <td><%= image.horiz_accuracy %></td>
    <td><%= image.vert_accuracy %></td>
    <td><%= image.location_confidence %></td>
    <td><%= link_to 'Show', image %></td>
    <td><%= link_to 'Edit', edit_image_path(image) %></td>
    <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Raw latitude:</b>
  <%= @image.raw_latitude %>
</p>

<p>
  <b>Raw longitude:</b>
  <%= @image.raw_longitude %>
</p>

<p>
  <b>Raw altitude:</b>
  <%= @image.raw_altitude %>
</p>

<p>
  <b>Horizontal accuracy:</b>
  <%= @image.horiz_accuracy %>
</p>

<p>
  <b>Vertical accuracy:</b>
  <%= @image.vert_accuracy %>
</p>

<p>
  <b>Best latitude:</b>
  <%= @image.best_latitude %>
</p>

<p>
  <b>Best longitude:</b>
  <%= @image.best_longitude %>
</p>

<p>
  <b>Best altitude:</b>
  <%= @image.best_altitude %>
</p>

<p>
  <b>Location confidence:</b>
  <%= @image.location_confidence %>
</p>

<p>
  <b>Raw yaw:</b>
  <%= @image.raw_yaw %>
</p>

<p>
  <b>Raw pitch:</b>
  <%= @image.raw_pitch %>
</p>

<p>
  <b>Raw roll:</b>
  <%= @image.raw_roll %>
</p>

<p>
  <b>Best yaw:</b>
  <%= @image.best_yaw %>
</p>

<p>
  <b>Best pitch:</b>
  <%= @image.best_pitch %>
</p>

<p>
  <b>Best roll:</b>
  <%= @image.best_roll %>
</p>

<p>
  <b>Raw qw:</b>
  <%= @image.raw_qw %>
</p>

<p>
  <b>Raw qx:</b>
  <%= @image.raw_qx %>
</p>

<p>
  <b>Raw qy:</b>
  <%= @image.raw_qy %>
</p>

<p>
  <b>Raw qz:</b>
  <%= @image.raw_qz %>
</p>

<p>
  <b>Best qw:</b>
  <%= @image.best_qw %>
</p>

<p>
  <b>Best qx:</b>
  <%= @image.best_qx %>
</p>

<p>
  <b>Best qy:</b>
  <%= @image.best_qy %>
</p>

<p>
  <b>Best qz:</b>
  <%= @image.best_qz %>
</p>

<p>
  <b>Description:</b>
  <%= @image.description %>
</p>

<p>
  <b>Category:</b>
  <%= @image.category %>
</p>

<p>
  <b>User:</b>
  <%= @image.user %>
</p>

<p>
  <b>Time Stamp:</b>
  <%= @image.time_stamp %>
</p>

<p>
  <b>Camera:</b>
  <%= @image.camera %>
</p>

<p>
  <b>Heading:</b>
  <%= @image.heading %>
</p>

<p>
  <b>Image:</b>
  <%= image_tag @image.image.url :thumb %>
</p>


<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>